version: '3'
services:
  db:
    ports:
      - 127.0.0.1:45432:5432
    image: postgres:13
    restart: unless-stopped
    command: postgres -c shared_buffers=256MB -c max_connections=500
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - meeting
      - the_world
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD", "pg_isready -U postgres -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  my_app_service:
    image: app
    env_file:
      - ./cmd/api/.env


networks:
  meeting:
    driver: overlay
  the_world:
    driver: bridge
