// Code generated by mockery v2.30.16. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/pichayaearn/meeting/pkg/model"
	mock "github.com/stretchr/testify/mock"
)

// CommentSvc is an autogenerated mock type for the CommentSvc type
type CommentSvc struct {
	mock.Mock
}

// Create provides a mock function with given fields: opts
func (_m *CommentSvc) Create(opts model.CreateCommentOpts) error {
	ret := _m.Called(opts)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.CreateCommentOpts) error); ok {
		r0 = rf(opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with given fields: opts, ctx
func (_m *CommentSvc) List(opts model.GetListCommentOpts, ctx context.Context) ([]model.Comment, error) {
	ret := _m.Called(opts, ctx)

	var r0 []model.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(model.GetListCommentOpts, context.Context) ([]model.Comment, error)); ok {
		return rf(opts, ctx)
	}
	if rf, ok := ret.Get(0).(func(model.GetListCommentOpts, context.Context) []model.Comment); ok {
		r0 = rf(opts, ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(model.GetListCommentOpts, context.Context) error); ok {
		r1 = rf(opts, ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCommentSvc creates a new instance of CommentSvc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCommentSvc(t interface {
	mock.TestingT
	Cleanup(func())
}) *CommentSvc {
	mock := &CommentSvc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
