name: e-comerce

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      
      - name: staticcheck
        run: |
          go mod download
          go get honnef.co/go/tools/cmd/staticcheck@2022.1
          staticcheck -checks all,-U1000,-ST1000 ./pkg/...

      - name: Build
        run: go build -v ./...

      - name: Run Unit Tests
        run: go test -v ./...





